export const IMAGE_SVG_XML_MIME_TYPE = 'image/svg+xml'
export const APPLICATION_MATHML_XML_MIME_TYPE = 'application/mathml+xml'
export const APPLICATION_XHTML_XML_MIME_TYPE = 'application/xhtml+xml'
export const APPLICATION_XML_MIME_TYPE = 'application/xml'
export const TEXT_HTML_MIME_TYPE = 'text/html'
