export {
  IMAGE_SVG_XML_MIME_TYPE,
  APPLICATION_MATHML_XML_MIME_TYPE,
  APPLICATION_XHTML_XML_MIME_TYPE,
  APPLICATION_XML_MIME_TYPE,
  TEXT_HTML_MIME_TYPE,
  HTML_ELEMENT_DEFAULT_MIME_TYPE_MAP,
} from './mimeTypes'
export {
  HTML_NAMESPACE,
  MATHML_NAMESPACE,
  SVG_NAMESPACE,
  XML_NAMESPACE,
  XLINK_NAMESPACE,
  XMLNS_NAMESPACE,
  XML_DEFAULT_NAMESPACE_MAP,
  SVG_DEFAULT_NAMESPACE_MAP,
  HTML_DEFAULT_NAMESPACE_MAP,
} from './namespaces'
